<template>
  <main class="exam-page" dir="rtl">
    <header class="topbar"><div class="brand"><span class="cap">🎓</span><span>منصة الاختبار</span></div><div class="status"><div class="timer"><span>◷</span><span>الوقت المتبقي</span><strong>{{ formattedTime }}</strong></div><div class="student"><span>{{ student?.name ?? '—' }}</span><div class="avatar">{{ student?.name?.charAt(0) ?? '؟' }}</div></div></div></header>
    <section v-if="loading" class="page-message">جارٍ تحميل الاختبار...</section>
    <section v-else-if="errorMessage" class="page-message error-message"><p>{{ errorMessage }}</p><button class="btn btn-navy" @click="initialize">إعادة المحاولة</button></section>
    <div v-else-if="currentQuestion" class="exam-shell">
      <aside class="sidebar"><h2>الأسئلة</h2><div class="q-grid"><button v-for="(question, index) in questions" :key="question.id" type="button" class="q-pill" :class="{ current: currentIndex === index, answered: !!answers[question.id], flagged: !!flags[question.id] }" @click="currentIndex = index">{{ index + 1 }}</button></div><div class="legend"><div class="legend-row"><span>تمت الإجابة</span><span class="swatch answered" /></div><div class="legend-row"><span>السؤال الحالي</span><span class="swatch current" /></div><div class="legend-row"><span>معلّم للمراجعة</span><span class="swatch flagged" /></div><div class="legend-row"><span>لم يُجب</span><span class="swatch unanswered" /></div></div><div class="spacer" /><div class="sidebar-actions"><button class="btn btn-outline" :class="{ flagged: currentFlagged }" :disabled="saving" @click="toggleFlag">🚩 {{ currentFlagged ? 'إلغاء التعليم' : 'تعليم للمراجعة' }}</button><button class="btn btn-red" :disabled="submitting" @click="submitExam">📤 {{ submitting ? 'جارٍ التسليم...' : 'تسليم الاختبار' }}</button></div></aside>
      <section class="exam-main"><div class="flag-banner" :class="{ show: currentFlagged }">⚑ تم تعيين هذا السؤال للمراجعة لاحقًا</div><article class="q-card"><p class="q-count">السؤال {{ currentIndex + 1 }} من {{ questions.length }}</p><p class="q-text">{{ currentQuestion.question }}</p><div class="options"><label v-for="option in currentQuestion.options" :key="option.id" class="option" :class="{ selected: answers[currentQuestion.id] === option.id }"><input type="radio" :name="`question-${currentQuestion.id}`" :value="option.id" :checked="answers[currentQuestion.id] === option.id" :disabled="saving" @change="selectAnswer(option.id)" /><span>{{ option.text }}</span></label></div><p v-if="saveError" class="error-text show">{{ saveError }}</p><nav class="q-nav"><button class="btn btn-outline" :disabled="currentIndex === 0" @click="currentIndex--">→ السابق</button><button v-if="currentIndex < questions.length - 1" class="btn btn-navy" @click="currentIndex++">التالي ←</button><button v-else class="btn btn-red" :disabled="submitting" @click="submitExam">تسليم الاختبار</button></nav></article></section>
    </div>
  </main>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import api from '../services/api'
import type { ApiResponse, Attempt, Exam, Question, Student } from '../types'
const router = useRouter(); const student = ref<Student | null>(null); const attemptId = ref<number | null>(null); const exam = ref<Exam | null>(null); const questions = ref<Question[]>([]); const currentIndex = ref(0); const answers = ref<Record<number, number>>({}); const flags = ref<Record<number, boolean>>({}); const loading = ref(true); const saving = ref(false); const submitting = ref(false); const errorMessage = ref(''); const saveError = ref(''); const timeLeft = ref(0); let timer: number | undefined
const currentQuestion = computed(() => questions.value[currentIndex.value]); const currentFlagged = computed(() => !!currentQuestion.value && !!flags.value[currentQuestion.value.id]); const formattedTime = computed(() => `${String(Math.floor(timeLeft.value / 60)).padStart(2, '0')}:${String(timeLeft.value % 60).padStart(2, '0')}`)
function getStudent(): Student | null { try { return JSON.parse(localStorage.getItem('exam_student') ?? 'null') } catch { return null } }
async function initialize() {
  clearInterval(timer); student.value = getStudent(); if (!student.value) { await router.replace('/login'); return }; loading.value = true; errorMessage.value = ''
  try { const examsResponse = await api.get<ApiResponse<Exam[]>>('/exams'); const firstExam = examsResponse.data.data[0]; if (!firstExam) throw new Error('لا يوجد اختبار متاح حاليًا.'); const [examResponse, attemptResponse] = await Promise.all([api.get<ApiResponse<Exam>>(`/exams/${firstExam.id}`), api.post<ApiResponse<Attempt>>('/attempts', { student_id: student.value.id, exam_id: firstExam.id })]); exam.value = examResponse.data.data; questions.value = exam.value.questions ?? []; attemptId.value = attemptResponse.data.data.id; if (!questions.value.length) throw new Error('لا يحتوي الاختبار على أسئلة.'); const started = new Date(attemptResponse.data.data.started_at).getTime(); timeLeft.value = Math.max(0, Math.floor((started + exam.value.duration_minutes * 60000 - Date.now()) / 1000)); timer = window.setInterval(() => { if (timeLeft.value <= 1) { timeLeft.value = 0; void submitExam() } else timeLeft.value-- }, 1000) }
  catch (err: any) { errorMessage.value = err.response?.data?.message ?? err.message ?? 'تعذر تحميل الاختبار.' }
  finally { loading.value = false }
}
async function selectAnswer(optionId: number) { if (!attemptId.value || !currentQuestion.value) return; const questionId = currentQuestion.value.id; const oldValue = answers.value[questionId]; answers.value[questionId] = optionId; saveError.value = ''; saving.value = true; try { await api.post(`/attempts/${attemptId.value}/answers`, { question_id: questionId, option_id: optionId }) } catch (err: any) { if (oldValue) answers.value[questionId] = oldValue; else delete answers.value[questionId]; saveError.value = err.response?.data?.message ?? 'تعذر حفظ الإجابة.' } finally { saving.value = false } }
async function toggleFlag() { if (!attemptId.value || !currentQuestion.value) return; const questionId = currentQuestion.value.id; const flagged = !flags.value[questionId]; flags.value[questionId] = flagged; saveError.value = ''; saving.value = true; try { await api.post(`/attempts/${attemptId.value}/flag`, { question_id: questionId, flagged }) } catch (err: any) { flags.value[questionId] = !flagged; saveError.value = err.response?.data?.message ?? 'تعذر حفظ حالة المراجعة.' } finally { saving.value = false } }
async function submitExam() { if (!attemptId.value || submitting.value) return; submitting.value = true; try { await api.post(`/attempts/${attemptId.value}/submit`); clearInterval(timer); await router.replace(`/result/${attemptId.value}`) } catch (err: any) { saveError.value = err.response?.data?.message ?? 'تعذر تسليم الاختبار.' } finally { submitting.value = false } }
onMounted(() => { void initialize() }); onUnmounted(() => clearInterval(timer))
</script>
